export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";


export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";

export const ASC_SORT_PRODUCTS_DATA = "ASC_SORT_PRODUCTS_DATA";
export const DESC_SORT_PRODUCTS_DATA = "DESC_SORT_PRODUCTS_DATA";